[package]
name = "mls"
version = "0.3.0"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
hex = "0.4"
base64 = "0.21"
bat = "0.24"

[dependencies.openmls]
git = "https://github.com/wireapp/openmls"
package = "openmls"
version = "1.0.0"
branch = "debug-pretty"
